blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/NeutrinoGamingStudios/Beta-Information/discussions
    about: For general questions or discussions about the beta, please use GitHub Discussions